### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by skellet0r** [EthBuilders/Curriculum#14]
We should add an issue template, so contributors have a standard for submitting feature requests, bug reports, and any other major possible issues which may arise.

A good example repository is https://github.com/stevemao/github-issue-templates/

More info about issue templates:
https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates

Excellent example of issue templates being used in the wild:
https://github.com/ipfs/newsletter/issues <= click create a new issue to see

**Comment by tesla809** [comment]
Superb idea! Agreed! It makes things easier for contributors and standardized issues.
