### ISSUE TITLE
[Content]: Add guide standardizing the structure of the website

### ISSUE THREAD

**Issue by skellet0r** [EthBuilders/Curriculum#18]
Editing pages is easy, but adding new pages is difficult.

The ramp for contributors to submit new content files, chapters, and pages should be simple, and requires a simple guide. Probably inside the Github wiki section. This way contributors can look in the wiki to find out how to make a new page/chapter.

**Comment by tesla809** [comment]
Good idea. We can use your well written Pull Request as a base for it.

**Comment by skellet0r** [comment]
Added to our repository wiki an initial guide on how the structure of the content is configured, and how this results in our site getting rendered.
<https://github.com/EthBuilders/Curriculum/wiki/Contributing-Content>

**Comment by skellet0r** [comment]
Resolved via Wiki

**Comment by tesla809** [comment]
AMAZING!!! STELLAR!!! @skellet0r !
