### ISSUE TITLE
move data from design_patterns.md to open_source.md

### ISSUE THREAD

**Issue by tesla809** [EthBuilders/Curriculum#2]
1. Create design_patterns.md

2. Move data from design_patterns.md to open_source.md.

**Comment by skellet0r** [comment]
Seems like one of those easy to grab issues to resolve.

I've added a commit to my fork but I've yet to add any content in the file so i'll most likely just discard it, but you can find it here - skellet0r/Curriculum@0cb2e1217d5ff52ab158e41adb0b422a9c431709

Looks like the following commits resolve item 2 of this issue:
9104433d6a927650037b6be1a6be0c43e0112ef6
b6c99de8bd9aa5fe98a0373103876b04e2c9c2cd

**Comment by tesla809** [comment]
Woohoo! Awesome contribution!
