### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by tesla809** [EthBuilders/Curriculum#3]
Create a CONTRIBUTING.md that has the standard rules of contributing to an open-source project.
Add a reference to open_source.md

CONTRIBUTING.md will also make reference to a style guide which will detail how a tutorial README.md will look like.

**Comment by skellet0r** [comment]
A few good examples for those looking to contribute to resolving this issue can be found below. These are examples from other well known open source projects here on GitHub.

- [ethereumbook/ethereumbook][gh-ethereumbook]: An excellent example [CONTRIBUTING.md][gh-ethereumbook-contrib]
- [atom/atom][gh-atom]: [CONTRIBUTING.md][gh-atom-contrib]
- [forem/forem][gh-forem]: [Contributor's Guide][gh-forem-contrib]
- [Template][template]: A good template example

These aren't definitive examples, and the use case for this repo is different from the ones listed above. However these are good general examples. Definitely look into other communities which distribute information/content such as [freeCodeCamp][1] and [StackExchange][2].


[1]: https://github.com/freeCodeCamp
[2]: https://github.com/StackExchange
[gh-atom]: https://github.com/atom/atom
[gh-atom-contrib]: https://github.com/atom/atom/blob/master/CONTRIBUTING.md
[gh-forem]: https://github.com/forem/forem "Framework behind the famous https://dev.to website"
[gh-forem-contrib]: https://docs.forem.com/contributing/forem/
[gh-ethereumbook]: https://github.com/ethereumbook/ethereumbook/ "A great resource as well"
[gh-ethereumbook-contrib]: https://github.com/ethereumbook/ethereumbook/blob/develop/CONTRIBUTING.md
[template]: https://gist.github.com/PurpleBooth/b24679402957c63ec426

**Comment by tesla809** [comment]
These are great suggestions @skellet0r!

 [Template](https://gist.github.com/PurpleBooth/b24679402957c63ec426) likes a great template example! It even has a good place to add the code of conduct. We can use it as a base for our CONTRIBUTING.md.

 Later we can  add to it with ideas from [forem/forem](https://github.com/forem/forem): [Contributor's Guide](https://docs.forem.com/contributing/forem/), [ethereumbook/ethereumbook](https://github.com/ethereumbook/ethereumbook/), and [freeCodeCamp](https://github.com/freeCodeCamp), and other good projects.

Great finds!

**Comment by tesla809** [comment]
@skellet0r Check out the contributing.md I forked from a previous project "CoronaTracker".

Any places we can simplify, edit down, make it easier to understand?
