### ISSUE TITLE
Maybe convert the Curriculum repository to a Static Website

### ISSUE THREAD

**Issue by skellet0r** [EthBuilders/Curriculum#6]
Might be a little excessive, but for those who don't use github/git it might be a pro. Especially if we'd like other people to contribute.
I was thinking we could use a static site generator like [hugo](https://gohugo.io/) since it makes building sites painless.

With a theme like [docsy](https://themes.gohugo.io/docsy/) it would look very nice ([Example site](https://example.docsy.dev/)).

Plus we could link it in with the EthBuilders/EthBuildersNYC-website when that gets up and running, and host it here on github, through [github pages](https://pages.github.com/) for simplicity.

**Comment by skellet0r** [comment]
I'd totally be down with converting us over, especially since we are still at a relatively early stage in the Curriculum repository in terms of content.

The information for how people would contribute moving forward would have to be included in the CONTRIBUTING.md (#3).

Pros:
- Still use markdown
- Hosted for free on github pages
- No need to install the hugo binaries for contributors 

Cons:
- Submitting new content would require a bit of frontmatter in markdown files

**Comment by tesla809** [comment]
Great idea! The pros seem very compelling!

Can you explain the con a bit more? What do you mean "would require a bit of frontmatter in markdown files".

**Comment by skellet0r** [comment]
Definitely @tesla809. I guess I should clarify and elaborate more on the pros/cons of switching over to a static site model.

## Cons

1. New submissions (new content markdown files) would require front matter in markdown files (#3)
   - Essentially whenever a new markdown content file is created, the creator would have to put a meta-data section at the top of the file.
   
   ```markdown
   ---
   <!-- Frontmatter section with content metadata -->
   title: "Solidity vs. Vyper 101"
   author: "Jane Doe"
   draft: false
   tags: ["languages", "programming"]
   categories: ["smart contract development", "blockchain"]
   ---
   <!-- Content would be beneath the metadata section, this is the content the end user would see -->
   Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
   incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud 
   exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure 
   dolor in reprehenderit in voluptate velit ...
   ```
   
2. For a completely automated system where the site is auto-deployed to production, we'd need to setup a CI/CD pipeline

3. If we use `github actions` for our CI/CD, we may need to use a master/dev branch structure or some form of tagging to prevent overusing the free allotment of `github actions` minutes per month.

4. Multiple languages requires multiple copies of the same file, just written in a different language.



## Pros

1. With content meta-data such as tags and categories, we can allow for easier indexing of content. For example someone only wants to see content with the tag "*truffle*", or just content edited/authored by "*Jane Doe*" and "*Jack Nicholas*"
2. There are many free CI/CD tools available but to keep things simple for organization we should use `github actions` and keep everything hosted together on the same platform
   - Each user/organization on the free tier gets 2,000 Actions minutes/month for free, and `hugo` takes milliseconds to build a static site. **Note: Additional time would have to be added (seconds) in overhead required for `github actions` to run**
3. Multiple languages support! Reaching a greater audience couldn't be easier, and it allows us to include people we wouldn't normally be able to communicate with.
4. With shortcodes (essentially like an html tag), contributors can include tweets, instagram posts, gists, youtube videos, vimeo videos in the content they submit
   - We can make shortcodes for anything, since they're essentially html templates/functions which you provide arguments to
5. Contributors don't really have to learn about hugo, they can just write/edit markdown files



Essentially for a curriculum/resources site using a static site generator, and even making the curriculum into a site not only differentiates our community, it would also be beneficial to individuals who don't really know how to do development. It also is beneficial for meetups, as everyone can follow along through the same site, no need to walk through a directory tree on GitHub. And tutorials from the meetup can be transcribed/recorded and hosted on the site for a consolidated place for people to reach it.

I don't think this is a definitive list, but just some things that I thought of since I initially submitted the issue. Overall I think it falls in line with the core idea of the [EthBuildersNYC-website](https://github.com/EthBuilders/EthBuildersNYC-website). Except that it's a little simpler since it's a static site.

Building stuff from scratch without money isn't easy but it is possible.

Some links I forgot to include:

shortcodes: https://gohugo.io/content-management/shortcodes/
hugo-site: https://gohugo.io/
github-pages-get-started: https://guides.github.com/features/pages/
github-actions: https://github.com/features/actions

**Comment by tesla809** [comment]
AMAZING! Exemplary explanation and a great suggestion!  

I agree with your points. Let's go with it!

It will simplify our process long term as well.

**Comment by chanhosuh** [comment]
I think there are good ideas here on how we would want to go in the future; however, I think time would be better spent for contributors to generate content, rather than expend effort on how to present currently non-existent content.

**Comment by skellet0r** [comment]
@chanhosuh you make a good point. A nice visual representation would be useless without the content. @tesla809 this issue should definitely go under a _future feature_ tag.

We could definitely come back to this idea after "**the basics**" content is complete, and determine if we should implement then.

**Comment by tesla809** [comment]
I say we start work on the visual representation now. That way we have the complete pipeline from idea generation to publication done.

Then, as our community grows and we standardize our contributing workflow, the content can be pushed quickly and effortlessly.

The idea is to experiment and iterate quickly.  What doesn't work is cut; what works is doubled down upon when validated by the community. 

What content is deemed missing is a great opportunity for contribution. We should aim to provide the tools and encouragement for our community to contribute at all levels.

**Comment by tesla809** [comment]
@chanhosuh @skellet0r we can all work asynchronously to get things done faster (and with good standards). 

@chanhosuh would you be able to focus on issue #3? That way we can set a firm foundation for future open source contributions.

@skellet0r can focus on setting up the CI/CD and static site that update upon pushing

The idea is that social proof and consistent, incremental improvement daily will yield a product of higher quality than trying to build the perfect thing before launch. See the [Kaizen method ](https://www.lucidchart.com/blog/kaizen-methodology#:~:text=Kaizen%20is%20a%20Japanese%20word,not%20just%20managers%20and%20executives.).

Social proof via consistent improvement will also excite current and future members to start to contribute making our work easier over time. Basically, we want to set the tone of the project and make people feel comfortable with contributing.

The idea is that we want members to:
1. **start** (the hardest part)
2. make a **SMALL** contribution daily (ideally a very small contribution to start)
3. **Improve** on their small contributions daily.
4. **SEE** the result of their contribution immediately. 
Feeling this the first time is key. Seeing this constantly is empowering.
5. Get **kudos** for contribution.
Feeling part of a community is also key. Social standing over time is also empowering.

**Comment by skellet0r** [comment]
@tesla809 on it, you can assign this issue to me.

**Comment by skellet0r** [comment]
@tesla809 @chanhosuh you can check out a WIP example of the conversion at https://skellet0r.github.io/Curriculum/
I'll be writing up / recording a more formal overview of the proposed changes when I submit the PR.

https://github.com/skellet0r/Curriculum/tree/hugo-conversion

**Comment by tesla809** [comment]
Looks FANTASTIC @skellet0r! Wow, I can really see the possibilities with this. Great suggestion!

For the logo, I just uploaded the one used for the meetup, along with the rainbow Eth logo. Check out how it looks using that one. Let me know what you think.

The site looks AMAZING so far!
